### PR TITLE
Merge for new glass shader

### PR DESCRIPTION
**Pull request by MWY3510**
I added the glass shader pipeline and fixed some spelling. If you plan on implementing an args parser don't worry about this pull request.

### CODE REVIEW

**Comment by gabyx** [comment]
Awesome :-) Will look over it soon, and merge :-)
Glass will help me too :-) I think in my renderings :-)

Thanks for the effort :-)

**Comment by gabyx** [comment]
the args parser would be good anyway, but it is not directly on the to do list, but would be good to have at the end :-)

**Comment by MWY3510** [comment]
Thanks for looking this over I had some interesting things happen when I was writing this. First this may just be my scene setup but some of the object turns black when rendering with glass you can see an example on the Blender to PRMAN plugin forum thread at Pixar. Second I did not implement the bumpnormal parameter as I did not know how to hook it up to the texture system.

   When I get some more free time I plan on implementing more shaders and documentation for the wiki, if you have a request let me know, if not I will try ether the pxrskin or one of the metal shaders. I will also try to separate bsavery's system for arg parsing and if someone gets permission will try to add to RIBMosic. I do not know how successful this will be however. It might be easier to write a parser just for this plugin.

   This is off topic but it would be a good idea I think to work with bsavery on his plugin, but because his does not work unless you have prman 20.0 RIBMosic is currently the only easy way of using prman and blender. When that version is released to the general public I would love to see a plugin as powerful as RIBMosic with the nodal fetures of PRman-for-blender.

**Comment by gabyx** [comment]
Jeah, for sure, thats definitely true about bsavery, 
You are totally free to try to come up with a args parsing stuff for RIBMosaic, i am also only an amateur what this tools concerns and struggled quite a lot improving it because its so crazy complex with all this XML stuff.
May be one could add the args parsing stuff with an Shader XML pipeline with a python script attached, I am not sure if that was the purpose of the python tags in the xml, I am not sure what they are used for so far :-) additional script stuff. The problem I see with bsavery's things is that it will be rather simple the tool I think, however having some really cool features as the node stuff things in blender which would be awseome to incorporate too in RIBmosaic, but I have no idea how, and my time is a bit limited :-)

I think its very good when you write some tutorial, as others can use this tool too, and so far it is working pretty ok, there some strange issues going on, with RNA properties dangling around in the blend file if the pipeline changes completely and so on :-)
I would not consider RIBmosaic an easy tool, its rather technical, and sometimes frustrating, but the code is well written =) for me it was not easy to understand most of the parts ? for you?

what the args parsing concerns, i would go with a python script, with XML ElementTree parse the stuff out and write the shader pipeline with all shaders for RIBmosaic :), how we would integrate that to make it upto date when the PATH to PRMAN changes i dont know :-). May be we can hook something up, the thing is, the shaderlibrary in RIBmosaic uses slmeta files (when there are already compiled shaders somewhere, no source available). it was intented that way I think such that we only provide the slmeta files for the shaders of pixar (for shaders where there are sources .sl files the COMPILE comand already should generate slmeta files, it did not work here so far, or I dont know what I am doing wrong,  it should generate somehow these files, at lease for the included shaders in RIBmosaic) and the COMPILE  xml tag could then be hooked upt with the xml parsing script for PRMAN which then just generates these slmeta files :-) (slmeta are also used in other open source software somehow) :-)
those are just random thoughts :-), sorry for my bad writting :-)

feel free to ask any question :-)

**Comment by gabyx** [comment]
Shouzld we not include the Glass shader just directly into the existing Surface shader
https://github.com/gabyx/RIBMosaic/blob/master/shader_library/renderman/Library_SurfaceRIS.rmp
instead of having a seperate file? :-)

**Comment by MWY3510** [comment]
I fixed my mistake. I forgot to merge my test file with the surface file :-). I am going to finish implementing the skin shader and then take a break to research the args parsing issue. At first glance I would go with the approach of reading the arg files and writing the rmp files for the pipeline. I think it might be possible to add a button to update the pipeline files only when the user downloads a new version of prman. Have you had a chance to look at the texture pipeline? To answar your question I have only scratched the surface of this plugin and really only understand the ui part. As to the nodes that would be a long term goal. I feel that a smooth basic pipeline should be the first goal to make the users job easier. 

Speaking of that in your example scene I noticed that prman pops up a new rendering window I am not able to replicate this with new files. I am wondering how you did that. I think it would be most effective to pop-up a new it process and have prman use it to render. This has the added benefit of allowing the user to stop the render when they think it is done. Right now the user cannot stop the render and must commit to finishing it because even it you close the window the prman task will continue. This is the case at least on windows.

If you find any other mistakes let me know. I would probably be good to take some time to talk about the future of the plugin. Thank you again for reviving this project!!

**Comment by MWY3510** [comment]
Sorry but I just couldn't help myself. I added two more shaders PxrDiffuse and PxrSkin. I apologize if this messes up your review schedule.

**Pull request merged**
